# Generated by Django 4.2.10 on 2024-04-10 01:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del tipo de video (p. ej. Fam. Gonzalez Torres, Cumpleanos, etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField(help_text='Ingrese una breve descripcion del video', max_length=1000)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.autor')),
                ('genero', models.ManyToManyField(help_text='Seleccione un genero para este video', to='catalogo.genre')),
            ],
        ),
        migrations.CreateModel(
            name='VideoInstancia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unico para este video particular en toda la biblioteca', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('m', 'Mantenimiento'), ('o', 'Viendo'), ('a', 'Disponible'), ('r', 'Reservado')], default='m', help_text='Disponibilidad del video', max_length=1)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.video')),
            ],
            options={
                'ordering': ['video'],
            },
        ),
    ]
